### PR TITLE
feat(walletManager): enable `agoric.chainWallet` deployment power

### PR DESCRIPTION
**Pull request by michaelfig**
refs: #2629

## Description

When the `agoric.chainWallet` deployment power is given (such as on the sim-chain), we create an on-chain wallet for that user.  It shares some purses with the ag-solo wallet (RUN, BLD, zoeFees), but has a different identity.

image

### Security Considerations

For now, the chain wallet has not been optimised, so it may pose a risk to an actual chain.  Fortunately, it is not created except via provisioning powers, which are currently only configurable by the holders of a "provisionpass".  We will need to migrate provisioning powers to on-chain governance, and should decide different policies for chainWallets as they become more useful.

### Documentation Considerations

`home.chainWallet` is an on-chain version of `home.wallet`.

### Testing Considerations

You can switch between the solo wallet and the chain wallet by running the following in the REPL and reloading the wallet UI after each

```js
home.wallet = agoric.chainWallet; // switch to chain wallet
home.wallet = local.wallet; // switch to ag-solo wallet
```

Watch the purses change in the below recording:

https://user-images.githubusercontent.com/457244/138399335-1baf73a1-de04-429e-9896-05da77cd9c39.mov

### CODE REVIEW

**Comment by dckc** [comment]
way to get started with something tangible!

I suggest:
refs: #2629

**Comment by samsiegart** [comment]
Just taking this chance to ask some questions for my understanding, perhaps I can find some of these answers in the docs:

1. > When the `agoric.chainWallet` deployment power is given (such as on the sim-chain)

The sim-chain is the local dev chain right? And otherwise, how would this power be given?

2. What is the cardinality/mapping of users to wallets when they're on-chain? For example, with the local wallet, it was one wallet running locally on each user's machine. Does every node now include a running wallet instance? Can they handle multiple users, or does a user have to do something to deploy a wallet instance? (This code looks different from a contract/api deploy script).

3. I assume we're not storing the users' keys on-chain, I think we are going to modify how on-chain wallet instances sign transactions, right?

**Comment by michaelfig** [comment]
> Just taking this chance to ask some questions for my understanding, perhaps I can find some of these answers in the docs:

👍 

> 1. > When the `agoric.chainWallet` deployment power is given (such as on the sim-chain)
> 
> The sim-chain is the local dev chain right? And otherwise, how would this power be given?

Yes, sim-chain is the local dev chain.  Otherwise, there's a `provisionpass` token that grants the holder the ability to provision a new client on the chain (via `agd tx swingset provision-one [nickname] [address] [powers]`), where the provisioned `powers` can include `agoric.chainWallet`.

> 1. What is the cardinality/mapping of users to wallets when they're on-chain? For example, with the local wallet, it was one wallet running locally on each user's machine. Does every node now include a running wallet instance? Can they handle multiple users, or does a user have to do something to deploy a wallet instance? (This code looks different from a contract/api deploy script).

There's currently one wallet backend vat for each user.  We can improve that later either for SwingSet to better support many vats, or to write a different wallet backend that is multiuser (which is probably bad from a risk partitioning standpoint).

> 2. I assume we're not storing the users' keys on-chain, I think we are going to modify how on-chain wallet instances sign transactions, right?

The on-chain wallet doesn't need to sign anything, because it's already on-chain (i.e. the crypto is for incoming messages to the wallet).  It'll be up to the wallet frontend (or `ag-solo`) to sign transactions to deliver to the chain, and eventually to counter-sign an authorisation to transfer assets via Zoe (which would be verified by the on-chain wallet).

**Review by katelynsills — APPROVED** [review]
this looks good to me! A nice feature of our distributed object capability system is that a huge move like this required no rewrite into another language! The same code works!

**Comment by samsiegart** [comment]
Thanks for the answers, LGTM!

**Review by samsiegart — APPROVED** [review]

**Pull request merged**
